# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

# need to install GDAL, see https://github.com/r-spatial/sf/blob/master/.travis.yml
sudo: required
dist: trusty
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

r:
  - release
  - devel

cache:
  - packages
